
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
      hibernate:
        connection:
          isolation: 1
  datasource:
    url: jdbc:mysql://database-1.cuwdhx9s5klh.ap-northeast-2.rds.amazonaws.com:3306/database1?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: ${MYSQL_SECRET}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  redis:
    host: localhost
    port: 6379

  data:
    redis:
      repositories:
        enabled: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  key: ${JWT_KEY}
  access-token-expiration-minutes: 1000
  refresh-token-expiration-minutes: 2000


logging:
  file:
    name: logs/logging.log
  level:
    spring:
      root: DEBUG
      com.server: DEBUG
      server:
        auth: DEBUG

#logging:
#  file:
#    name: logs/logging.log
#  level:
#    root: DEBUG
#    spring:
#      root: DEBUG
#      com:
#        server:
#          auth: DEBUG


cors:
  allowed-origins: "*"
  allowed-methods: GET, POST, PATCH, DELETE, OPTIONS
  allowed-headers: Authorization, Content-Type
  allow-credentials: true
